# Splunk props.conf - sourcetype definitions

[access_combined]
TIME_FORMAT = %d/%b/%Y:%H:%M:%S %z
SHOULD_LINEMERGE = false
MAX_TIMESTAMP_LOOKAHEAD = 40

[auth_events]
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
KV_MODE = json
SHOULD_LINEMERGE = false

[sysmon_json]
KV_MODE = json
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%3NZ
SHOULD_LINEMERGE = false
