# Cortex 3 minimal configuration for SOC lab
search {
  index: cortex
  uri: "http://elasticsearch:9200"
}
play.http.secret.key: "ThisIsASecretKeyForSOCLabOnlyNotForProduction"
cache.job: 10 minutes
job {
  runner: [docker]
}
docker.pullImage: Missing
